// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRqGS4jR-JChAoNx2HFlFl5jTF2anPeDI',
    appId: '1:101387223450:web:f9823f5645ecc348cfba23',
    messagingSenderId: '101387223450',
    projectId: 'trackizer-3c612',
    authDomain: 'trackizer-3c612.firebaseapp.com',
    storageBucket: 'trackizer-3c612.firebasestorage.app',
    measurementId: 'G-5525MTS3W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV7HBy_4sdaP0vI4DVv_agmeZvRn_J2Ks',
    appId: '1:101387223450:android:00a4937ee1b7853ccfba23',
    messagingSenderId: '101387223450',
    projectId: 'trackizer-3c612',
    storageBucket: 'trackizer-3c612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESL3iMMwfrlLZVWD-EEYg4AwYbo1uPzw',
    appId: '1:101387223450:ios:838863cdc68ac235cfba23',
    messagingSenderId: '101387223450',
    projectId: 'trackizer-3c612',
    storageBucket: 'trackizer-3c612.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESL3iMMwfrlLZVWD-EEYg4AwYbo1uPzw',
    appId: '1:101387223450:ios:838863cdc68ac235cfba23',
    messagingSenderId: '101387223450',
    projectId: 'trackizer-3c612',
    storageBucket: 'trackizer-3c612.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRqGS4jR-JChAoNx2HFlFl5jTF2anPeDI',
    appId: '1:101387223450:web:e4ceee4e429e43e6cfba23',
    messagingSenderId: '101387223450',
    projectId: 'trackizer-3c612',
    authDomain: 'trackizer-3c612.firebaseapp.com',
    storageBucket: 'trackizer-3c612.firebasestorage.app',
    measurementId: 'G-LYJCF630MX',
  );
}
